authentication/models.py
import hashlib
from urllib.parse import urlencode
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from .choices import GENDER_CHOICES,ROLE_CHOICES,EDUCATION_CHOICES, MENTORSHIP_AREAS_CHOICES
from multiselectfield import MultiSelectField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

DEFAULT = 'profiles/default.jpg'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=50, default='')
    bio = models.TextField(default='')
    gender = models.CharField(
        max_length=6,
        choices=GENDER_CHOICES,
        default=''
        )
    role = models.CharField(
        max_length=6,
        blank=False,
        default='mentee',
        choices=ROLE_CHOICES
        )
    phone_number = models.CharField(max_length=32, default='')
    mentorship_areas = MultiSelectField(
        choices=MENTORSHIP_AREAS_CHOICES,
        default=''
        )
    highest_level_of_study = models.CharField(
        max_length=255,
        choices=EDUCATION_CHOICES,
        default=''
        )
    is_previously_logged_in = models.CharField(max_length=5, default=False)
    email_confirmed = models.BooleanField(default=False)
    profile_picture = ProcessedImageField(
        upload_to='profiles',
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 99},
        default=DEFAULT,
        )

    def is_mentor(self):
        return self.role == 'mentor'

    def is_mentee(self):
        return self.role == 'mentee'

    class Meta:
        db_table = 'auth_profile'

    def __str__(self):
        return self.user.username

    def get_screen_name(self):
        if self.user.get_full_name():
            return self.user.get_full_name()
        else:
            return self.user.username

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class UserCode(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=6)


class Interest(models.Model):
    user = models.OneToOneField(
        User,
        blank = True, on_delete = models.CASCADE)
    stem = models.BooleanField(blank = True, default = False)
    entrepreneurship = models.BooleanField(blank = True, default = False)
    career_counseling = models.BooleanField(blank = True, default = False)
    career_readiness = models.BooleanField(
        db_column = "career_readiness",
        verbose_name = 'career_readiness',
        blank = True, default = False)
    addictions = models.BooleanField(blank = True, default = False)

    class Meta:
        db_table = "interests"

    def __unicode__(self):
        return unicode(self.user.username)


class Connection(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mentor = models.IntegerField(null=False)
    status = models.IntegerField(null=False, default=0)

    def __unicode__(self):
        return unicode(self.user)

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .choices import ROLE_CHOICES



def invalid_username_validator(value):
    if '@' in value or '+' in value or '-' in value:
        raise ValidationError('Enter a valid username.')


def unique_email_validator(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError('User with this Email already exists.')


def unique_username_ignore_case_validator(value):
    if User.objects.filter(username__iexact=value).exists():
        raise ValidationError('User with this Username already exists.')


class SignUpForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'md-form-control'}),
        max_length=30,
        required=True,
        # help_text='Usernames may contain alphanumeric, _ and . characters'
        )  # noqa: E261
    email = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'md-form-control'}),
        # help_text='Required. Inform a valid email address.',
        required=True,
        max_length=75)
    role = forms.ChoiceField(
        choices=ROLE_CHOICES,
        initial='',
        widget=forms.Select(attrs={'class': 'md-form-control'}),
        required=True,
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'md-form-control'}))
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'md-form-control'}),
        label="Confirm your password",
        required=True)

    class Meta:
        model = User
        exclude = ['last_login', 'date_joined']
        fields = ['username', 'email', 'role', 'password', 'confirm_password', ]

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].validators.append(forbidden_usernames_validator)
        self.fields['username'].validators.append(invalid_username_validator)
        self.fields['username'].validators.append(
            unique_username_ignore_case_validator)
        self.fields['email'].validators.append(unique_email_validator)

    def clean(self):
        super(SignUpForm, self).clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and password != confirm_password:
            self._errors['password'] = self.error_class(
                ['Passwords don\'t match'])
        return self.cleaned_data

authentication/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from authentication.forms import SignUpForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from authentication.tokens import account_activation_token

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = User.objects.create_user(username=username, password=password,
                                     email=email)
            user.refresh_from_db()
            user.profile.role = form.cleaned_data.get('role')
            user.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/account/login/')
    else:
        form = SignUpForm()
    return render(request, 'authentication/signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'authentication/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('/')
    else:
        return render(request, 'authentication/account_activation_invalid.html')

authentication/templates/authentication/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

authentication/templates/authentication/account_activation_invalid.html
{% extends 'base.html' %}

{% block body %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

authentication/templates/authentication/account_activation_sent.html
{% extends 'base.html' %}

{% block body %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

authentication/templates/authentication/password_reset.html
{% load i18n %}

{% block title %}Password reset{% endblock %}

{% block body_id %}password-reset{% endblock %}

{% block main %}
<div id='login' class='module'>
    <div class='module-head'>
        <h3>Password reset</h3>
    </div>
    <div class='module-body'>
      <p>Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one.</p>
      
      <form action="" method="post">{% csrf_token %}
          {{ form.email.errors }}
          <p><label for="id_email">{% trans 'E-mail address:' %}</label> {{ form.email }} </p>
          <p> <input type="submit" value="{% trans 'Reset password' %}" /> </p>
      </form>
    </div>
    <div class="module-foot">
    </div>
</div>
{% endblock main %}

authentication/templates/authentication/password_reset_complete.html
{% load i18n %}

{% block title %}
Password reset complete 
{% endblock title %}

{% block body_id %}password-reset-complete{% endblock %}

{% block main %}
<div id='login' class='module'>
    <div class='module-head'>
        <h3>Password reset complete</h3>
    </div>
    <div class='module-body'>
      <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
    </div>
    <div class="module-foot">
    </div>
</div>

{% endblock main %}

authentication/templates/authentication/password_reset_confirm.html
{% load i18n %}

{% block title %}Password reset confirmation{% endblock %}
{% block body_id %}password-reset-confirmation{% endblock %}

{% block main %}
<div id='login' class='module'>
    <div class='module-head'>
        <h3>Password reset</h3>
    </div>
    <div class='module-body'>
      {% if validlink %}
      
      <h1>{% trans 'Enter new password' %}</h1>
      
      <p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
      
      <form action="" method="post">{% csrf_token %}
	{{ form.new_password1.errors }}
	<p class="aligned wide"><label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}</p>
	{{ form.new_password2.errors }}
	<p class="aligned wide"><label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}</p>
	<p><input type="submit" value="{% trans 'Change my password' %}" /></p>
      </form>
      
      {% else %}
      
      <h1>{% trans 'Password reset unsuccessful' %}</h1>
      
      <p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}
	
	{% endif %}
	
    </div>
    <div class="module-foot">
    </div>
    
</div>
{% endblock main %}

authentication/templates/authentication/password_reset_done.html
{% load i18n %}

{% block title %}Password reset successful{% endblock %}

{% block body_id %}password-reset-successful{% endblock %}

{% block main %}
<div id='login' class='module'>
    <div class='module-head'>
        <h3>Password reset successful</h3>
    </div>
    <div class='module-body'>
      <p>{% trans "We've e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly." %}</p>
    </div>
    <div class="module-foot">
    </div>
</div>

{% endblock main %}

authentication/templates/authentication/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% trans "You're receiving this e-mail because you requested a password reset" %}
{% blocktrans %}for your user account at {{ site_name }}{% endblocktrans %}.

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

authentication/templates/authentication/signup.html
{% extends 'base.html' %}

{% block main %}
<div class="container" >
<div class="row">
    <div class="col-md-3 col-sm-3"></div>

    <div class="col-md-6 col-sm-6 panel panel-default" style="background-color: transparent; margin-top: 20px">

        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              {{ error }}
            </div>
          {% endfor %}
        {% endif %}

        <div class="panel-body">
        <h2>{% trans 'Account Signup' %}</h2>
        <hr/>
          <form role="form" class="form-horizontal" method="post" action="{% url 'signup' %}">
            {% csrf_token %}
            {% for field in form.visible_fields %}
              <div class="form-group{% if field.errors %} has-error{% endif %} ">
                <label for="{{ field.label }}" class="col-md-3 control-label">{{ field.label }}:</label>
                <div class="col-md-9">
                  {{ field }}
                  {% if field.help_text %}
                    <span class="help-block">{{ field.help_text }}</span>
                  {% endif %}
                  {% for error in field.errors %}
                    <label class="control-label">{{ error }}</label>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-3 col-sm-3"></div>
            <div class="col-md-9 col-sm-9">
              <button type="submit" class="btn btn-primary">{% trans 'Next' %}</button>
              <a href="{% url 'login' %}">{% trans 'Login to MentorMe' %}</a>
            </div>
          </form>
      </div>
    </div>
    </div>
</div>
{% endblock main %}